# Generated by Django 4.1.5 on 2023-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercer', '0002_alter_userinfo_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.TextField(default=None),
        ),
    ]
