# Generated by Django 4.1.5 on 2023-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercer', '0005_product_category_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdesc', models.TextField(default=None)),
                ('sdesc', models.TextField(default=None)),
                ('tname', models.TextField(default=None)),
                ('tphoto', models.TextField(default=None)),
                ('services', models.TextField(default=None)),
            ],
        ),
    ]
