# Generated by Django 4.1.5 on 2023-06-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercer', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='tphoto',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
