# Generated by Django 4.1.5 on 2023-06-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercer', '0007_alter_about_tphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='abouts',
        ),
    ]
